version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal_backend
    image: personal-backend-image:latest
    ports:
      - "8000:${NODE_PORT}"
    environment:
      - DB_HOST=database
      - TEST_DB_HOST=testdatabase
    depends_on:
      - database
    volumes:
      - .:/app
    networks:
      - personal_network

  database:
    image: postgres
    container_name: personal_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    networks:
      - personal_network

  testdatabase:
    image: postgres
    container_name: personal_testdatabase
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"
    command: -p ${TEST_DB_PORT}
    networks:
      - personal_network

volumes:
  db_data:
    name: personal_db_data
  test_db_data:
    name: personal_test_db_data

networks:
  personal_network:
    name: personal_network
