import { Knex } from "knex";

exports.seed = async function (knex: Knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      country: "Nepal",
      username: "nirajan_bist",
      email: "admin@example.com",
      full_name: "Nirajan Bist",
      department: "Development",
      designation: "Developer",
      contact: "9812345678",
      role: "Admin",
    },
    {
      id: 2,
      country: "USA",
      username: "john_doe",
      email: "john.doe@example.com",
      full_name: "John Doe",
      department: "IT",
      designation: "Developer",
      contact: "9812345678",
      role: "Admin",
    },
    {
      id: 3,
      country: "UK",
      username: "jane_smith",
      email: "jane.smith@example.com",
      full_name: "Jane Smith",
      department: "HR",
      designation: "Manager",
      contact: "9823456789",
      role: "Manager",
    },
    {
      id: 4,
      country: "India",
      username: "mike_williams",
      email: "mike.williams@example.com",
      full_name: "Mike Williams",
      department: "Finance",
      designation: "Accountant",
      contact: "9834567890",
      role: "Employee",
    },
    {
      id: 5,
      country: "Canada",
      username: "emily_jones",
      email: "emily.jones@example.com",
      full_name: "Emily Jones",
      department: "Sales",
      designation: "Executive",
      contact: "9845678901",
      role: "Employee",
    },
    {
      id: 6,
      country: "Australia",
      username: "david_clark",
      email: "david.clark@example.com",
      full_name: "David Clark",
      department: "Marketing",
      designation: "Analyst",
      contact: "9856789012",
      role: "Employee",
    },
    {
      id: 7,
      country: "Germany",
      username: "lisa_miller",
      email: "lisa.miller@example.com",
      full_name: "Lisa Miller",
      department: "Operations",
      designation: "Supervisor",
      contact: "9867890123",
      role: "Employee",
    },
    {
      id: 8,
      country: "France",
      username: "kevin_adams",
      email: "kevin.adams@example.com",
      full_name: "Kevin Adams",
      department: "Research",
      designation: "Scientist",
      contact: "9878901234",
      role: "Employee",
    },
    {
      id: 9,
      country: "Japan",
      username: "sarah_taylor",
      email: "sarah.taylor@example.com",
      full_name: "Sarah Taylor",
      department: "Engineering",
      designation: "Engineer",
      contact: "9889012345",
      role: "Employee",
    },
    {
      id: 10,
      country: "Brazil",
      username: "michael_brown",
      email: "michael.brown@example.com",
      full_name: "Michael Brown",
      department: "Legal",
      designation: "Lawyer",
      contact: "9890123456",
      role: "Employee",
    },
    {
      id: 11,
      country: "China",
      username: "amy_lee",
      email: "amy.lee@example.com",
      full_name: "Amy Lee",
      department: "Customer Support",
      designation: "Representative",
      contact: "9891234567",
      role: "Employee",
    },
  ]);

  await knex.raw(`ALTER SEQUENCE users_id_seq RESTART WITH 12;`);
};
